server:
  port: 9999    # 项目端口
  servlet:
    context-path: /admin  # 项目访问路径

spring:
  application:
    name: @project.artifactId@  # 服务名称，取 pom.xml 中的 artifactId
  # 上传文件大小限制
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件最大
      max-request-size: 100MB # 接收的最大请求大小
  cloud:
    nacos:  # 单机版本关闭nacos 服务发现和配置管理的能力
      config:
        enabled: false
      discovery:
        enabled: false
  freemarker: # freemarker 配置，授权码模式页面渲染使用
    suffix: .ftl
    template-loader-path: classpath:/templates/
    request-context-attribute: request
  thymeleaf: # thymeleaf 配置，标准评估页面渲染使用
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  main:
    allow-bean-definition-overriding: true # 允许覆盖bean定义
  profiles:
    active: dev  # 激活dev，对应 application-dev.yml


## spring security 对外暴露接口设置（不鉴权直接可访问）
security:
  micro: false
  oauth2:
    ignore:
      urls:
        - /webjars/**
        - /v3/api-docs/**
        - /doc.html
        - /swagger-ui.html
        - /swagger-ui/**
        - /swagger-resources
        - /code/image
        - /error
        - /token/**
        - /actuator/**
        - /evaluation/**  # 标准评估模块无需登录
        - /admin/evaluation/**  # 标准评估模块无需登录（带context-path）

#--------------如下配置尽量不要变动-------------
# swagger 配置
swagger:
  token-url: ${swagger.gateway}/admin/oauth2/token

# AI模型配置
ai:
  # 当前使用的模型：deepseek 或 kimi
  current-model: kimi
  
  # DeepSeek配置
  deepseek:
    use_mock_data: false
    api:
      url: https://api.deepseek.com/v1/chat/completions
      key: sk-4de8748b8bd84085957b446e1810ae9d
      model: deepseek-chat
      temperature: 0.2
      max_tokens: 3000
      stream: false
      timeout: 300000
    prompt:
      file: classpath:prompts/evaluation-prompt-fast.txt
  
  # Kimi配置
  kimi:
    use_mock_data: false
    api:
      url: https://api.moonshot.cn/v1/chat/completions
      key: sk-oN08WRFLwiOcbILNF2Fw8dnOrUdAlROOtB1ZKGn02Q315rST
      model: moonshot-v1-8k # moonshot-v1-128k
      temperature: 0.2
      max_tokens: 3000
      stream: false
      timeout: 300000
    prompt:
      file: classpath:prompts/evaluation-prompt-kimi.txt
  
  # 本地模型配置（Ollama）
  local:
    enabled: true  # 本地模型开关，设置为true启用本地模型
    use_mock_data: false
    api:
      url: http://localhost:11434/api/generate  # Ollama默认端口
      model: qwen2.5:7b-instruct  # 本地模型名称，推荐中文稳定
      temperature: 0.2
      max_tokens: 3000
      timeout: 300000
    prompt:
      file: classpath:prompts/evaluation-prompt.txt

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml # mapper文件位置
  global-config:
    banner: false # 是否打印 mybatis-plus banner
    db-config:
      id-type: auto  # 主键类型
      where-strategy: not_empty # where 条件策略
      insert-strategy: not_empty # 插入策略
      update-strategy: not_null  # 更新策略
  type-handlers-package: com.pig4cloud.pig.common.mybatis.handler # 类型处理器包
  configuration:
    jdbc-type-for-null: 'null' # 是否设置字段为null
    call-setters-on-nulls: true # 是否调用set方法时传入null值
    shrink-whitespaces-in-sql: true # 去掉sql中多余的空格
